# Generated by Django 3.2.3 on 2021-11-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dept', models.IntegerField(unique=True)),
                ('ubicacion', models.CharField(max_length=30)),
                ('estado_departamento', models.BooleanField()),
                ('habitaciones', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
