# Generated by Django 3.2.3 on 2021-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reserva.departamento'),
            preserve_default=False,
        ),
    ]
