# Generated by Django 3.2.3 on 2021-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_cliente_id_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=20)),
                ('comprobante', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_funcionario', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicio', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=40)),
                ('valor_servicio', models.FloatField()),
            ],
        ),
    ]
